### ISSUE TITLE
Filter section UI issue in course creation

### ISSUE THREAD

**Issue by Jayaprakash8887** [project-sunbird/sunbird-commons#52] opened 2017-09-13 09:15 UTC
Dear Team,

Go to Workspace --> Create new course --> Click on Add a story/collection/worksheet --> Filter section in the search modal window is cluttered.

Warm regards,
JP

**Comment by Abhign** [comment] 2017-09-15 04:51
@Jayaprakash8887 this issue got fixed in the last release, now i have check it is not replaceable.

**Comment by kochhar** [comment] 2017-10-09 06:18
@Jayaprakash8887 @Abhign If the problem is fixed, can this issue be closed?

**Comment by Jayaprakash8887** [comment] 2017-10-09 06:29
Dear Shailesh,

This can be still seen at times. Guessing it should be replicable in
systems with weak connections.

Warm regards,
JP

**Comment by kochhar** [comment] 2017-10-09 08:28
@Jayaprakash8887 thanks, please add this issue to JIRA. You can coordinate with Vinod to answer any questions on how to add to JIRA.

**Closed** 2017-10-11 09:13 UTC
Labels: from users
