### ISSUE TITLE
Mobile Authentication failure #Bodhi

### ISSUE THREAD

**Issue by rajooda** [project-sunbird/sunbird-commons#104] opened 2017-11-07 12:44 UTC
Getting a jsonResponse after the keyCloak Authentication.

{"error":"invalid_grant","error_description":"Code is expired"}

#bodhi

**Comment by AmiableAnil** [comment] 2017-11-08 11:10
@rajooda When this error is occurring while signin or signup. Currently signup its not working in mobile app.

**Comment by rajooda** [comment] 2017-11-08 11:30
What is the solution for this?

**The Logcat Error I am seeing is:**

[INFO:CONSOLE(140)] "Uncaught TypeError: Cannot read property 'call' of undefined", source: file:///android_asset/index_bundle.js (140)

Response{protocol=http/1.1, code=401, message=Unauthorized, url=https://staging.open-sunbird.org/api/user/v1/update/logintime}

[INFO:CONSOLE(35699)] "login patch call", source: file:///android_asset/index_bundle.js (35699)

**Comment by AmiableAnil** [comment] 2017-11-09 06:51
@rajooda Could you tell the steps to reproduce this issue.

**Comment by rajooda** [comment] 2017-11-10 05:47
It is direct build of the github code. The authentication with keycloak is successfull and then the above error is thrown in LogCat. I see few more changes have been done to the code. I will take those changes and then share the diff with the LogCat

**Comment by rajooda** [comment] 2017-11-10 06:46
@AmiableAnil 

I have gist for you with LogCat and build.gradle at

https://gist.github.com/rajooda/9577fdd3d064ce0ed886d180d4c7726a

**Comment by rajooda** [comment] 2017-11-10 12:32
@AmiableAnil 

Hi Anil, 

What are these variables?
mentioned at L95 and L96?

https://github.com/project-sunbird/sunbird-mobile/blob/master/app/build.gradle#L95

How do I get these? I am trying to hitting:
https://staging.open-sunbird.org

**Comment by AmiableAnil** [comment] 2017-11-13 11:31
@rajooda 
You need to generate key and secret for `mobile_app` user using JWT token of `mobile_admin` user.

Please find the steps here
[https://github.com/project-sunbird/sunbird-devops/blob/master/Installation.md#step-6-generate-key-and-secrets-for-mobile-app](https://github.com/project-sunbird/sunbird-devops/blob/master/Installation.md#step-6-generate-key-and-secrets-for-mobile-app)

**Comment by AmiableAnil** [comment] 2017-11-16 05:47
@rajooda 

Hi Rajeev,

Please let me know if the above issue is resolved or not?

**Comment by kochhar** [comment] 2017-11-21 10:56
closing this issue since it seems resolved.

**Closed** 2017-11-21 10:56 UTC
Labels: docs-bug, from users
